import json
import tempfile
import unittest
from pathlib import Path

from Tools.map_generator import RecipeError, generate_map, write_map
from Tools.map_validator import MapValidator

ROOT = Path(__file__).resolve().parents[2]
TILES_PATH = ROOT / "Mods" / "Dimensionfall" / "Tiles" / "Tiles.json"
FURNITURES_PATH = ROOT / "Mods" / "Dimensionfall" / "Furniture" / "Furniture.json"
MOBS_PATH = ROOT / "Mods" / "Dimensionfall" / "Mobs" / "Mobs.json"
MOBGROUPS_PATH = ROOT / "Mods" / "Dimensionfall" / "Mobgroups" / "Mobgroups.json"
ITEMGROUPS_PATH = ROOT / "Mods" / "Dimensionfall" / "Itemgroups" / "Itemgroups.json"


def valid_recipe():
    return {
        "id": "generated_test_map",
        "name": "Generated Test Map",
        "description": "Generated by a unit test.",
        "seed": 12345,
        "base_tile": {"id": "grass_plain_01", "rotation": "random"},
        "regions": [],
    }


class MapGeneratorTests(unittest.TestCase):
    def test_successful_generation_has_complete_map_shape(self):
        generated = generate_map(valid_recipe(), TILES_PATH)

        self.assertEqual(generated["id"], "generated_test_map")
        self.assertEqual(generated["name"], "Generated Test Map")
        self.assertEqual(generated["description"], "Generated by a unit test.")
        self.assertEqual(generated["mapwidth"], 32)
        self.assertEqual(generated["mapheight"], 32)
        self.assertEqual(generated["categories"], [])
        self.assertEqual(generated["weight"], 1000)
        self.assertEqual(
            generated["connections"],
            {
                "north": "ground",
                "east": "ground",
                "south": "ground",
                "west": "ground",
            },
        )
        self.assertEqual(len(generated["levels"]), 21)
        self.assertTrue(all(level == [] for level in generated["levels"][:10]))
        self.assertEqual(len(generated["levels"][10]), 1024)
        self.assertTrue(all(level == [] for level in generated["levels"][11:]))

    def test_generation_is_deterministic_for_the_same_seed(self):
        first = generate_map(valid_recipe(), TILES_PATH)
        second = generate_map(valid_recipe(), TILES_PATH)

        self.assertEqual(first, second)
        self.assertEqual(
            [tile.get("rotation", 0) for tile in first["levels"][10][:12]],
            [270, 0, 180, 180, 90, 180, 270, 90, 180, 0, 270, 180],
        )

    def test_legacy_regions_and_every_operation_can_target_logical_z(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["patterns"] = {
            "one": [{"at": [0, 0], "tile": {"id": "grass_flowers_01"}}]
        }
        recipe["regions"] = [
            {
                "x": 1,
                "y": 1,
                "z": -1,
                "width": 2,
                "height": 1,
                "tile": {"id": "dirt_light_00"},
            }
        ]
        recipe["operations"] = [
            {
                "type": "set",
                "x": 1,
                "y": 1,
                "z": 1,
                "tile": {"id": "dirt_light_00"},
            },
            {
                "type": "rectangle",
                "x": 2,
                "y": 1,
                "z": 1,
                "width": 2,
                "height": 1,
                "tile": {"id": "dirt_light_00"},
            },
            {
                "type": "rectangle_outline",
                "x": 4,
                "y": 1,
                "z": 1,
                "width": 2,
                "height": 2,
                "tile": {"id": "dirt_light_00"},
            },
            {
                "type": "line",
                "from": [6, 1],
                "to": [7, 1],
                "z": 1,
                "tile": {"id": "dirt_light_00"},
            },
            {
                "type": "scatter",
                "region": {"x": 8, "y": 1, "width": 1, "height": 1},
                "count": 1,
                "z": 1,
                "tile": {"id": "dirt_light_00"},
            },
            {"type": "pattern", "pattern": "one", "at": [9, 1], "z": 1},
        ]

        levels = generate_map(recipe, TILES_PATH)["levels"]

        self.assertEqual(len(levels[9]), 1024)
        self.assertEqual(levels[9][1 * 32 + 1], {"id": "dirt_light_00"})
        self.assertEqual(len(levels[10]), 1024)
        self.assertEqual(len(levels[11]), 1024)
        for x in range(1, 9):
            self.assertEqual(levels[11][1 * 32 + x], {"id": "dirt_light_00"})
        self.assertEqual(levels[11][1 * 32 + 9], {"id": "grass_flowers_01"})
        self.assertTrue(all(level == [] for level in levels[:9]))
        self.assertTrue(all(level == [] for level in levels[12:]))

    def test_grouped_levels_apply_in_declaration_order_with_local_overwrites(self):
        recipe = valid_recipe()
        del recipe["base_tile"]
        del recipe["regions"]
        recipe["levels"] = [
            {
                "z": 1,
                "base_tile": {"id": "grass_plain_01"},
                "regions": [
                    {
                        "x": 2,
                        "y": 2,
                        "width": 2,
                        "height": 1,
                        "tile": {"id": "dirt_light_00"},
                    }
                ],
                "operations": [
                    {"type": "set", "x": 2, "y": 2, "tile": None}
                ],
            },
            {"z": 0, "base_tile": {"id": "dirt_light_00"}},
        ]

        levels = generate_map(recipe, TILES_PATH)["levels"]

        self.assertEqual(levels[11][2 * 32 + 2], {})
        self.assertEqual(levels[11][2 * 32 + 3], {"id": "dirt_light_00"})
        self.assertTrue(all(tile == {"id": "dirt_light_00"} for tile in levels[10]))

    def test_grouped_levels_are_deterministic_and_consume_rng_in_declaration_order(self):
        recipe = valid_recipe()
        recipe["seed"] = 19
        recipe["palette"] = {
            "ground": [
                {"id": "grass_plain_01", "weight": 1},
                {"id": "grass_flowers_00", "weight": 1},
            ]
        }
        del recipe["base_tile"]
        del recipe["regions"]
        recipe["levels"] = [
            {"z": 1, "base_tile": {"palette": "ground"}},
            {"z": 0, "base_tile": {"palette": "ground"}},
        ]

        first = generate_map(recipe, TILES_PATH)
        second = generate_map(recipe, TILES_PATH)

        self.assertEqual(first, second)
        self.assertEqual(
            [tile["id"] for tile in first["levels"][11][:6]],
            [
                "grass_plain_01",
                "grass_plain_01",
                "grass_plain_01",
                "grass_flowers_00",
                "grass_flowers_00",
                "grass_flowers_00",
            ],
        )
        self.assertEqual(
            [tile["id"] for tile in first["levels"][10][:3]],
            ["grass_flowers_00", "grass_flowers_00", "grass_plain_01"],
        )

    def test_grouped_levels_reject_ambiguous_or_malformed_definitions(self):
        cases = [
            ({"levels": []}, "levels must be a non-empty array"),
            ({"levels": [42]}, r"levels\[0\] must be an object"),
            ({"levels": [{}]}, r"levels\[0\].z is required"),
            (
                {"levels": [{"z": 0}, {"z": 0}]},
                r"levels\[1\].z duplicates logical level 0",
            ),
            (
                {"levels": [{"z": 0, "extra": True}]},
                r"unknown levels\[0\] field 'extra'",
            ),
        ]
        for changes, expected_message in cases:
            with self.subTest(changes=changes):
                recipe = valid_recipe()
                del recipe["base_tile"]
                del recipe["regions"]
                recipe.update(changes)
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

        recipe = valid_recipe()
        recipe["levels"] = [{"z": 1}]
        with self.assertRaisesRegex(
            RecipeError, "recipe.base_tile cannot be combined with recipe.levels"
        ):
            generate_map(recipe, TILES_PATH)

    def test_logical_z_rejects_boolean_and_out_of_range_values(self):
        for invalid_z in (-11, 11, True, 1.5, "1"):
            with self.subTest(invalid_z=invalid_z):
                recipe = valid_recipe()
                recipe["operations"] = [
                    {
                        "type": "set",
                        "x": 0,
                        "y": 0,
                        "z": invalid_z,
                        "tile": None,
                    }
                ]
                with self.assertRaisesRegex(
                    RecipeError, "must be an integer between -10 and 10"
                ):
                    generate_map(recipe, TILES_PATH)

    def test_grouped_operations_inherit_z_and_reject_nested_z(self):
        recipe = valid_recipe()
        del recipe["base_tile"]
        del recipe["regions"]
        recipe["levels"] = [
            {
                "z": -1,
                "operations": [
                    {"type": "set", "x": 0, "y": 0, "z": -1, "tile": None}
                ],
            }
        ]

        with self.assertRaisesRegex(
            RecipeError, "must be omitted because the enclosing level defines z"
        ):
            generate_map(recipe, TILES_PATH)

    def test_explicit_level_with_only_empty_tiles_remains_unused(self):
        recipe = valid_recipe()
        del recipe["base_tile"]
        del recipe["regions"]
        recipe["levels"] = [
            {
                "z": 3,
                "operations": [
                    {"type": "set", "x": 0, "y": 0, "tile": None}
                ],
            }
        ]

        self.assertEqual(generate_map(recipe, TILES_PATH)["levels"][13], [])

    def test_rectangular_regions_replace_tiles_in_row_major_grid(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["regions"] = [
            {
                "x": 1,
                "y": 1,
                "width": 2,
                "height": 2,
                "tile": {"id": "dirt_light_00", "rotation": 90},
            }
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        expected_region_indexes = {33, 34, 65, 66}
        for index, tile in enumerate(level):
            if index in expected_region_indexes:
                self.assertEqual(tile, {"id": "dirt_light_00", "rotation": 90})
            else:
                self.assertEqual(tile, {"id": "grass_plain_01"})

    def test_null_region_tile_uses_the_existing_empty_dictionary_representation(self):
        recipe = valid_recipe()
        recipe["regions"] = [{"x": 0, "y": 0, "width": 1, "height": 1, "tile": None}]

        generated = generate_map(recipe, TILES_PATH)

        self.assertEqual(generated["levels"][10][0], {})

    def test_set_operation_places_one_tile(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {"type": "set", "x": 3, "y": 2, "tile": {"id": "dirt_light_00"}}
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        self.assertEqual(level[2 * 32 + 3], {"id": "dirt_light_00"})
        self.assertEqual(level[2 * 32 + 2], {"id": "grass_plain_01"})

    def test_furniture_operation_embeds_known_feature_on_explicit_logical_level(self):
        recipe = valid_recipe()
        recipe["operations"] = [
            {
                "type": "set",
                "x": 4,
                "y": 5,
                "z": 1,
                "tile": {"id": "grass_plain_01"},
            },
            {
                "type": "furniture",
                "x": 4,
                "y": 5,
                "z": 1,
                "id": "bench_garden",
                "rotation": 90,
            },
        ]

        levels = generate_map(
            recipe, TILES_PATH, furnitures_path=FURNITURES_PATH
        )["levels"]

        self.assertEqual(
            levels[11][5 * 32 + 4],
            {
                "id": "grass_plain_01",
                "feature": {
                    "type": "furniture",
                    "id": "bench_garden",
                    "rotation": 90,
                    "itemgroups": [],
                },
            },
        )

    def test_grouped_furniture_inherits_level_and_defaults_rotation(self):
        recipe = valid_recipe()
        del recipe["base_tile"]
        del recipe["regions"]
        recipe["levels"] = [
            {
                "z": -1,
                "base_tile": {"id": "grass_plain_01"},
                "operations": [
                    {"type": "furniture", "x": 3, "y": 2, "id": "Tree_00"}
                ],
            }
        ]

        tile = generate_map(recipe, TILES_PATH)["levels"][9][2 * 32 + 3]

        self.assertEqual(tile["feature"]["rotation"], 0)
        self.assertEqual(tile["feature"]["id"], "Tree_00")

    def test_furniture_requires_terrain_and_rejects_feature_conflicts(self):
        recipe = valid_recipe()
        recipe["operations"] = [
            {
                "type": "furniture",
                "x": 1,
                "y": 1,
                "z": 1,
                "id": "bench_garden",
            }
        ]
        with self.assertRaisesRegex(RecipeError, "requires supporting terrain"):
            generate_map(recipe, TILES_PATH)

        recipe = valid_recipe()
        recipe["operations"] = [
            {"type": "furniture", "x": 1, "y": 1, "id": "bench_garden"},
            {"type": "furniture", "x": 1, "y": 1, "id": "Tree_00"},
        ]
        with self.assertRaisesRegex(RecipeError, "conflicts with an existing feature"):
            generate_map(recipe, TILES_PATH)

    def test_later_tile_operation_explicitly_replaces_furniture_feature(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {"type": "furniture", "x": 1, "y": 1, "id": "bench_garden"},
            {"type": "set", "x": 1, "y": 1, "tile": {"id": "dirt_light_00"}},
        ]

        tile = generate_map(recipe, TILES_PATH)["levels"][10][1 * 32 + 1]

        self.assertEqual(tile, {"id": "dirt_light_00"})


    def test_furniture_scatter_uses_weighted_palette_on_eligible_cells_only(self):
        recipe = valid_recipe()
        recipe["seed"] = 41
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["furniture_palette"] = {
            "forest": [
                {"id": "Tree_00", "weight": 3, "rotation": "random"},
                {"id": "PineTree_00", "weight": 1, "rotation": 90},
            ]
        }
        recipe["operations"] = [
            {"type": "furniture", "x": 1, "y": 1, "id": "bench_garden"},
            {"type": "set", "x": 2, "y": 1, "tile": None},
            {
                "type": "furniture_scatter",
                "region": {"x": 0, "y": 0, "width": 4, "height": 2},
                "count": 6,
                "palette": "forest",
            },
        ]

        first = generate_map(recipe, TILES_PATH)
        second = generate_map(recipe, TILES_PATH)
        level = first["levels"][10]
        scattered = [
            (index % 32, index // 32, tile["feature"])
            for index, tile in enumerate(level)
            if tile.get("feature", {}).get("id") in {"Tree_00", "PineTree_00"}
        ]

        self.assertEqual(first, second)
        self.assertEqual(len(scattered), 6)
        self.assertTrue(all(0 <= x < 4 and 0 <= y < 2 for x, y, _ in scattered))
        self.assertFalse(level[1 * 32 + 1].get("feature", {}).get("id") in {"Tree_00", "PineTree_00"})
        self.assertEqual(level[1 * 32 + 1]["feature"]["id"], "bench_garden")
        self.assertEqual(level[1 * 32 + 2], {})
        self.assertTrue(
            all(feature["rotation"] in {0, 90, 180, 270} for _, _, feature in scattered)
        )

    def test_furniture_scatter_rejects_insufficient_eligible_cells(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["furniture_palette"] = {"forest": [{"id": "Tree_00"}]}
        recipe["operations"] = [
            {"type": "furniture", "x": 0, "y": 0, "id": "bench_garden"},
            {
                "type": "furniture_scatter",
                "region": {"x": 0, "y": 0, "width": 2, "height": 1},
                "count": 2,
                "palette": "forest",
            },
        ]

        with self.assertRaisesRegex(RecipeError, "requests 2 placements but only 1 eligible"):
            generate_map(recipe, TILES_PATH)

    def test_grouped_furniture_scatter_inherits_logical_level_and_uses_density(self):
        recipe = valid_recipe()
        del recipe["base_tile"]
        del recipe["regions"]
        recipe["furniture_palette"] = {"forest": [{"id": "Tree_00"}]}
        recipe["levels"] = [
            {
                "z": 1,
                "base_tile": {"id": "grass_plain_01"},
                "operations": [
                    {
                        "type": "furniture_scatter",
                        "region": {"x": 0, "y": 0, "width": 3, "height": 3},
                        "density": 0.5,
                        "palette": "forest",
                    }
                ],
            }
        ]

        levels = generate_map(recipe, TILES_PATH)["levels"]

        self.assertEqual(
            sum(
                tile.get("feature", {}).get("id") == "Tree_00"
                for tile in levels[11]
            ),
            4,
        )
        self.assertEqual(levels[10], [])

    def test_furniture_palette_and_scatter_strictly_validate_schema(self):
        cases = [
            (
                {"furniture_palette": {"forest": [{"id": "missing"}]}},
                "unknown furniture 'missing'",
            ),
            (
                {"furniture_palette": {"forest": [{"id": "Tree_00", "weight": 0}]}},
                "weight must be a positive integer",
            ),
            (
                {"furniture_palette": {"forest": [{"id": "Tree_00", "rotation": 45}]}},
                "rotation must be 0, 90, 180, 270, or 'random'",
            ),
            (
                {
                    "operations": [
                        {
                            "type": "furniture_scatter",
                            "region": {"x": 0, "y": 0, "width": 1, "height": 1},
                            "count": 1,
                            "palette": "missing",
                        }
                    ]
                },
                "unknown furniture palette 'missing'",
            ),
            (
                {
                    "furniture_palette": {"forest": [{"id": "Tree_00"}]},
                    "operations": [
                        {
                            "type": "furniture_scatter",
                            "region": {"x": 0, "y": 0, "width": 1, "height": 1},
                            "count": 1,
                            "palette": "forest",
                            "extra": True,
                        }
                    ],
                },
                r"unknown operations\[0\] field 'extra'",
            ),
        ]
        for changes, expected_message in cases:
            with self.subTest(changes=changes):
                recipe = valid_recipe()
                recipe.update(changes)
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_furniture_operation_strictly_validates_schema_id_and_rotation(self):
        cases = [
            (
                {"type": "furniture", "x": 1, "y": 1, "id": "missing"},
                "unknown furniture 'missing'",
            ),
            (
                {"type": "furniture", "x": 1, "y": 1, "id": ""},
                "id must be a non-empty string",
            ),
            (
                {
                    "type": "furniture",
                    "x": 1,
                    "y": 1,
                    "id": "bench_garden",
                    "rotation": "random",
                },
                "rotation must be 0, 90, 180, or 270",
            ),
            (
                {
                    "type": "furniture",
                    "x": 1,
                    "y": 1,
                    "id": "bench_garden",
                    "extra": True,
                },
                r"unknown operations\[0\] field 'extra'",
            ),
        ]
        for operation, expected_message in cases:
            with self.subTest(operation=operation):
                recipe = valid_recipe()
                recipe["operations"] = [operation]
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_terrain_only_recipe_does_not_require_furniture_database(self):
        with tempfile.TemporaryDirectory() as directory:
            tiles_path = Path(directory) / "Tiles.json"
            tiles_path.write_text(
                json.dumps([{"id": "grass_plain_01"}]), encoding="utf-8"
            )
            recipe = valid_recipe()
            recipe["base_tile"] = {"id": "grass_plain_01"}

            generated = generate_map(recipe, tiles_path)

        self.assertEqual(generated["levels"][10][0], {"id": "grass_plain_01"})

    def test_rectangle_operation_is_filled_and_later_operations_overwrite(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {
                "type": "rectangle",
                "x": 1,
                "y": 1,
                "width": 3,
                "height": 2,
                "tile": {"id": "dirt_light_00"},
            },
            {"type": "set", "x": 2, "y": 1, "tile": None},
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        for index in {33, 35, 65, 66, 67}:
            self.assertEqual(level[index], {"id": "dirt_light_00"})
        self.assertEqual(level[34], {})

    def test_rectangle_outline_places_only_border_and_handles_thin_rectangles(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {
                "type": "rectangle_outline",
                "x": 1,
                "y": 1,
                "width": 3,
                "height": 3,
                "tile": {"id": "dirt_light_00"},
            },
            {
                "type": "rectangle_outline",
                "x": 6,
                "y": 1,
                "width": 1,
                "height": 3,
                "tile": None,
            },
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        self.assertEqual(level[2 * 32 + 2], {"id": "grass_plain_01"})
        for x, y in ((1, 1), (2, 1), (3, 1), (1, 2), (3, 2), (1, 3), (2, 3), (3, 3)):
            self.assertEqual(level[y * 32 + x], {"id": "dirt_light_00"})
        for y in range(1, 4):
            self.assertEqual(level[y * 32 + 6], {})

    def test_line_operation_handles_horizontal_vertical_and_diagonal_lines(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {
                "type": "line",
                "from": [1, 1],
                "to": [4, 1],
                "tile": {"id": "dirt_light_00"},
            },
            {
                "type": "line",
                "from": [6, 1],
                "to": [6, 4],
                "tile": {"id": "dirt_light_00"},
            },
            {
                "type": "line",
                "from": [8, 1],
                "to": [11, 4],
                "tile": None,
            },
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        for x in range(1, 5):
            self.assertEqual(level[1 * 32 + x], {"id": "dirt_light_00"})
        for y in range(1, 5):
            self.assertEqual(level[y * 32 + 6], {"id": "dirt_light_00"})
        for x, y in ((8, 1), (9, 2), (10, 3), (11, 4)):
            self.assertEqual(level[y * 32 + x], {})

    def test_scatter_count_is_exact_deterministic_and_replaces_existing_tiles(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {
                "type": "scatter",
                "region": {"x": 4, "y": 5, "width": 4, "height": 3},
                "count": 5,
                "tile": {"id": "dirt_light_00"},
            }
        ]

        first = generate_map(recipe, TILES_PATH)["levels"][10]
        second = generate_map(recipe, TILES_PATH)["levels"][10]
        scattered = {
            (index % 32, index // 32)
            for index, tile in enumerate(first)
            if tile == {"id": "dirt_light_00"}
        }

        self.assertEqual(first, second)
        self.assertEqual(len(scattered), 5)
        self.assertTrue(all(4 <= x < 8 and 5 <= y < 8 for x, y in scattered))

    def test_scatter_density_uses_floor_of_region_area(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["operations"] = [
            {
                "type": "scatter",
                "region": {"x": 0, "y": 0, "width": 3, "height": 3},
                "density": 0.5,
                "tile": {"id": "dirt_light_00"},
            }
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        self.assertEqual(level.count({"id": "dirt_light_00"}), 4)

    def test_pattern_operation_places_relative_cells_with_quarter_turn_rotation(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["patterns"] = {
            "corner": [
                {"at": [0, 0], "tile": {"id": "dirt_light_00"}},
                {"at": [1, 0], "tile": {"id": "grass_flowers_01"}},
                {"at": [0, 1], "tile": None},
            ]
        }
        recipe["operations"] = [
            {
                "type": "pattern",
                "pattern": "corner",
                "at": [10, 10],
                "rotation": 90,
            }
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        self.assertEqual(level[10 * 32 + 10], {"id": "dirt_light_00"})
        self.assertEqual(level[11 * 32 + 10], {"id": "grass_flowers_01"})
        self.assertEqual(level[10 * 32 + 9], {})

    def test_pattern_cells_and_later_operations_follow_ordered_overwrite_semantics(
        self,
    ):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["patterns"] = {
            "overlap": [
                {"at": [0, 0], "tile": {"id": "dirt_light_00"}},
                {"at": [0, 0], "tile": {"id": "grass_flowers_01"}},
            ]
        }
        recipe["operations"] = [
            {"type": "pattern", "pattern": "overlap", "at": [4, 5]},
            {"type": "set", "x": 4, "y": 5, "tile": None},
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        self.assertEqual(level[5 * 32 + 4], {})

    def test_pattern_palette_selection_is_deterministic(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["palette"] = {
            "detail": [
                {"id": "grass_flowers_00", "weight": 1, "rotation": "random"},
                {"id": "grass_flowers_01", "weight": 1, "rotation": "random"},
            ]
        }
        recipe["patterns"] = {
            "details": [
                {"at": [0, 0], "tile": {"palette": "detail"}},
                {"at": [1, 0], "tile": {"palette": "detail"}},
                {"at": [2, 0], "tile": {"palette": "detail"}},
            ]
        }
        recipe["operations"] = [
            {"type": "pattern", "pattern": "details", "at": [5, 5]}
        ]

        first = generate_map(recipe, TILES_PATH)
        second = generate_map(recipe, TILES_PATH)

        self.assertEqual(first, second)

    def test_unused_pattern_definition_does_not_change_rng_order(self):
        recipe = valid_recipe()
        expected = generate_map(recipe, TILES_PATH)
        recipe["patterns"] = {
            "unused": [
                {
                    "at": [0, 0],
                    "tile": {"id": "grass_flowers_00", "rotation": "random"},
                }
            ]
        }

        self.assertEqual(generate_map(recipe, TILES_PATH), expected)

    def test_pattern_definitions_are_strictly_validated_even_when_unused(self):
        cases = [
            ({"patterns": []}, "patterns must be an object"),
            (
                {"patterns": {"": [{"at": [0, 0], "tile": None}]}},
                "pattern names must be non-empty strings",
            ),
            (
                {"patterns": {"bad name": [{"at": [0, 0], "tile": None}]}},
                "may contain only letters",
            ),
            (
                {"patterns": {"empty": []}},
                "patterns.empty must be a non-empty array",
            ),
            (
                {"patterns": {"bad": [42]}},
                r"patterns.bad\[0\] must be an object",
            ),
            (
                {"patterns": {"bad": [{"tile": None}]}},
                r"patterns.bad\[0\].at is required",
            ),
            (
                {"patterns": {"bad": [{"at": [0, 0]}]}},
                r"patterns.bad\[0\].tile is required",
            ),
            (
                {"patterns": {"bad": [{"at": [True, 0], "tile": None}]}},
                "must be a two-integer array",
            ),
            (
                {
                    "patterns": {
                        "bad": [{"at": [0, 0], "tile": None, "extra": 1}]
                    }
                },
                r"unknown patterns.bad\[0\] field 'extra'",
            ),
            (
                {
                    "patterns": {
                        "bad": [
                            {"at": [0, 0], "tile": {"id": "missing_tile"}}
                        ]
                    }
                },
                "unknown tile 'missing_tile'",
            ),
        ]
        for changes, expected_message in cases:
            with self.subTest(changes=changes):
                recipe = valid_recipe()
                recipe.update(changes)
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_pattern_operations_reject_invalid_references_fields_and_bounds(self):
        base_pattern = {"patterns": {"one": [{"at": [1, 0], "tile": None}]}}
        cases = [
            (
                {"type": "pattern", "pattern": "missing", "at": [1, 1]},
                "unknown pattern 'missing'",
            ),
            (
                {"type": "pattern", "pattern": "one", "at": [1]},
                "must be a two-integer array",
            ),
            (
                {
                    "type": "pattern",
                    "pattern": "one",
                    "at": [1, 1],
                    "rotation": "random",
                },
                "rotation must be 0, 90, 180, or 270",
            ),
            (
                {
                    "type": "pattern",
                    "pattern": "one",
                    "at": [1, 1],
                    "extra": 1,
                },
                r"unknown operations\[0\] field 'extra'",
            ),
            (
                {"type": "pattern", "pattern": "one", "at": [31, 0]},
                "outside the 32x32 map at \\[32, 0\\]",
            ),
        ]
        for operation, expected_message in cases:
            with self.subTest(operation=operation):
                recipe = valid_recipe()
                recipe.update(base_pattern)
                recipe["operations"] = [operation]
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_invalid_operations_are_rejected_with_clear_errors(self):
        base_region = {"x": 0, "y": 0, "width": 2, "height": 2}
        cases = [
            ("not-an-array", "operations must be an array"),
            ([{"type": "unknown"}], "unknown operation 'unknown'"),
            (
                [{"type": "set", "x": 32, "y": 0, "tile": None}],
                "operations\\[0\\].x must be an integer between 0 and 31",
            ),
            (
                [{"type": "set", "x": 0, "y": 0, "tile": None, "extra": 1}],
                "unknown operations\\[0\\] field 'extra'",
            ),
            (
                [
                    {
                        "type": "rectangle",
                        "x": 31,
                        "y": 0,
                        "width": 2,
                        "height": 1,
                        "tile": None,
                    }
                ],
                "extends outside the 32x32 map",
            ),
            (
                [{"type": "line", "from": [0, 0], "to": [32, 0], "tile": None}],
                "operations\\[0\\].to\\[0\\] must be an integer between 0 and 31",
            ),
            (
                [{"type": "scatter", "region": base_region, "tile": None}],
                "must define exactly one of count or density",
            ),
            (
                [
                    {
                        "type": "scatter",
                        "region": base_region,
                        "count": 1,
                        "density": 0.5,
                        "tile": None,
                    }
                ],
                "must define exactly one of count or density",
            ),
            (
                [
                    {
                        "type": "scatter",
                        "region": base_region,
                        "count": 5,
                        "tile": None,
                    }
                ],
                "count must be an integer between 0 and 4",
            ),
            (
                [
                    {
                        "type": "scatter",
                        "region": base_region,
                        "count": 0,
                        "tile": {"id": "missing_tile"},
                    }
                ],
                "unknown tile 'missing_tile'",
            ),
            (
                [
                    {
                        "type": "scatter",
                        "region": base_region,
                        "density": True,
                        "tile": None,
                    }
                ],
                "density must be a number between 0 and 1",
            ),
            (
                [
                    {
                        "type": "scatter",
                        "region": {**base_region, "extra": 1},
                        "count": 1,
                        "tile": None,
                    }
                ],
                "unknown operations\\[0\\].region field 'extra'",
            ),
        ]
        for operations, expected_message in cases:
            with self.subTest(operations=operations):
                recipe = valid_recipe()
                recipe["operations"] = operations
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_operations_require_an_explicit_tile_field(self):
        operations = [
            {"type": "set", "x": 0, "y": 0},
            {"type": "rectangle", "x": 0, "y": 0, "width": 1, "height": 1},
            {
                "type": "rectangle_outline",
                "x": 0,
                "y": 0,
                "width": 1,
                "height": 1,
            },
            {"type": "line", "from": [0, 0], "to": [1, 1]},
            {
                "type": "scatter",
                "region": {"x": 0, "y": 0, "width": 1, "height": 1},
                "count": 0,
            },
        ]
        for operation in operations:
            with self.subTest(operation=operation):
                recipe = valid_recipe()
                recipe["operations"] = [operation]
                with self.assertRaisesRegex(
                    RecipeError, "operations\\[0\\].tile is required"
                ):
                    generate_map(recipe, TILES_PATH)

    def test_invalid_recipes_are_rejected_with_clear_errors(self):
        cases = [
            (
                {"id": "../unsafe"},
                "id may contain only letters, numbers, underscores, and hyphens",
            ),
            ({"base_tile": {"id": "missing_tile"}}, "unknown tile 'missing_tile'"),
            (
                {"regions": [{"x": 0, "width": "two", "height": 1, "tile": None}]},
                "regions\\[0\\].y must be a non-negative integer",
            ),
            (
                {
                    "regions": [
                        {
                            "x": 31,
                            "y": 31,
                            "width": 2,
                            "height": 1,
                            "tile": None,
                        }
                    ]
                },
                "extends outside the 32x32 map",
            ),
            ({"unexpected": True}, "unknown recipe field 'unexpected'"),
            (
                {
                    "regions": [
                        {
                            "x": 0,
                            "y": 0,
                            "width": 1,
                            "height": 1,
                            "tile": None,
                            "unexpected": True,
                        }
                    ]
                },
                "unknown regions\\[0\\] field 'unexpected'",
            ),
            (
                {"base_tile": {"id": "grass_plain_01", "unexpected": True}},
                "unknown base_tile field 'unexpected'",
            ),
        ]
        for changes, expected_message in cases:
            with self.subTest(changes=changes):
                recipe = valid_recipe()
                recipe.update(changes)
                with self.assertRaisesRegex(ValueError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_palette_reference_works_for_base_tile(self):
        recipe = valid_recipe()
        recipe["palette"] = {
            "ground": [
                {"id": "grass_plain_01", "weight": 1},
                {"id": "grass_flowers_00", "weight": 1},
            ]
        }
        recipe["base_tile"] = {"palette": "ground"}

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        self.assertTrue(
            all(tile["id"] in {"grass_plain_01", "grass_flowers_00"} for tile in level)
        )
        self.assertGreater(len({tile["id"] for tile in level}), 1)

    def test_palette_reference_works_for_rectangle_and_scatter_operations(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "grass_plain_01"}
        recipe["palette"] = {
            "path": [{"id": "dirt_light_00", "weight": 1}],
            "flowers": [{"id": "grass_flowers_01", "weight": 1}],
        }
        recipe["operations"] = [
            {
                "type": "rectangle",
                "x": 1,
                "y": 1,
                "width": 2,
                "height": 2,
                "tile": {"palette": "path"},
            },
            {
                "type": "scatter",
                "region": {"x": 10, "y": 10, "width": 3, "height": 3},
                "count": 3,
                "tile": {"palette": "flowers"},
            },
        ]

        level = generate_map(recipe, TILES_PATH)["levels"][10]

        for index in {33, 34, 65, 66}:
            self.assertEqual(level[index], {"id": "dirt_light_00"})
        self.assertEqual(level.count({"id": "grass_flowers_01"}), 3)

    def test_weighted_palette_selection_is_deterministic_and_uses_weights(self):
        recipe = valid_recipe()
        recipe["seed"] = 7
        recipe["palette"] = {
            "ground": [
                {"id": "grass_plain_01", "weight": 8},
                {"id": "grass_flowers_00", "weight": 2},
            ]
        }
        recipe["base_tile"] = {"palette": "ground"}

        first = generate_map(recipe, TILES_PATH)["levels"][10]
        second = generate_map(recipe, TILES_PATH)["levels"][10]
        flower_count = first.count({"id": "grass_flowers_00"})
        grass_count = first.count({"id": "grass_plain_01"})

        self.assertEqual(first, second)
        self.assertGreater(flower_count, 0)
        self.assertGreater(grass_count, flower_count)

    def test_palette_validation_rejects_malformed_entries_and_references(self):
        cases = [
            ({"base_tile": {"palette": "missing"}}, "unknown palette 'missing'"),
            ({"palette": []}, "palette must be an object"),
            (
                {"palette": {"": [{"id": "grass_plain_01"}]}},
                "palette names must be non-empty strings",
            ),
            (
                {"palette": {"bad name": [{"id": "grass_plain_01"}]}},
                "may contain only letters",
            ),
            ({"palette": {"ground": []}}, "palette.ground must be a non-empty array"),
            (
                {"palette": {"ground": ["grass_plain_01"]}},
                r"palette.ground\[0\] must be an object",
            ),
            (
                {"palette": {"ground": [{"weight": 1}]}},
                "must define exactly one of id or palette",
            ),
            (
                {"palette": {"ground": [{"id": "missing_tile"}]}},
                "unknown tile 'missing_tile'",
            ),
            (
                {"palette": {"ground": [{"id": "grass_plain_01", "weight": 0}]}},
                "weight must be a positive integer",
            ),
            (
                {"palette": {"ground": [{"id": "grass_plain_01", "rotation": 45}]}},
                "rotation must be 0, 90, 180, 270, or 'random'",
            ),
            (
                {"palette": {"ground": [{"id": "grass_plain_01", "extra": True}]}},
                r"unknown palette.ground\[0\] field 'extra'",
            ),
            (
                {
                    "palette": {"ground": [{"id": "grass_plain_01"}]},
                    "base_tile": {"id": "grass_plain_01", "palette": "ground"},
                },
                "base_tile must define exactly one of id or palette",
            ),
        ]
        for changes, expected_message in cases:
            with self.subTest(changes=changes):
                recipe = valid_recipe()
                recipe.update(changes)
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_recipe_dimensions_are_not_configurable(self):
        for field in ("width", "height"):
            with self.subTest(field=field):
                recipe = valid_recipe()
                recipe[field] = 32
                with self.assertRaisesRegex(
                    RecipeError, f"unknown recipe field '{field}'"
                ):
                    generate_map(recipe, TILES_PATH)

    def test_example_recipes_generate_successfully(self):
        cases = {
            "map_recipe.json": {10},
            "map_recipe_furniture_outdoor.json": {10},
            "map_recipe_two_level_hill.json": {10, 11},
            "map_recipe_two_level_depression.json": {9, 10},
        }
        for filename, expected_populated_indices in cases.items():
            with self.subTest(filename=filename):
                recipe_path = ROOT / "Tools" / "examples" / filename
                generated = generate_map(
                    json.loads(recipe_path.read_text(encoding="utf-8")), TILES_PATH
                )

                self.assertEqual(generated["mapwidth"], 32)
                self.assertEqual(generated["mapheight"], 32)
                self.assertEqual(
                    {
                        index
                        for index, level in enumerate(generated["levels"])
                        if level
                    },
                    expected_populated_indices,
                )
                for index in expected_populated_indices:
                    self.assertEqual(len(generated["levels"][index]), 1024)

    def test_furniture_example_uses_known_features_on_supported_ground_tiles(self):
        recipe_path = ROOT / "Tools" / "examples" / "map_recipe_furniture_outdoor.json"
        generated = generate_map(
            json.loads(recipe_path.read_text(encoding="utf-8")), TILES_PATH
        )
        furniture_ids = {
            tile["feature"]["id"]
            for tile in generated["levels"][10]
            if tile.get("feature", {}).get("type") == "furniture"
        }
        furniture_tiles = [
            tile
            for tile in generated["levels"][10]
            if tile.get("feature", {}).get("type") == "furniture"
        ]

        self.assertTrue(
            {"bench_garden", "campfire_off", "plant_pot_00"}.issubset(furniture_ids)
        )
        self.assertTrue(
            furniture_ids <= {
                "Tree_00",
                "PineTree_00",
                "WillowTree_00",
                "burned_tree_stump",
                "rock_field_00",
                "wild_vegetation_00",
                "bench_garden",
                "campfire_off",
                "plant_pot_00",
            }
        )
        self.assertEqual(len(furniture_tiles), 43)
        self.assertTrue(
            any(
                tile["feature"]["id"] in {
                    "Tree_00",
                    "PineTree_00",
                    "WillowTree_00",
                    "burned_tree_stump",
                }
                for tile in furniture_tiles
            )
        )
        self.assertTrue(
            all(
                tile.get("id")
                for tile in generated["levels"][10]
                if tile.get("feature", {}).get("type") == "furniture"
            )
        )

    def test_outdoor_rock_and_wild_vegetation_assets_are_known_and_referenced(self):
        furniture_data = json.loads(FURNITURES_PATH.read_text(encoding="utf-8"))
        furniture_by_id = {entry["id"]: entry for entry in furniture_data}
        recipe_path = ROOT / "Tools" / "examples" / "map_recipe_furniture_outdoor.json"
        recipe = json.loads(recipe_path.read_text(encoding="utf-8"))

        for furniture_id, expected_sprite in {
            "rock_field_00": "ai_rock_32_32.png",
            "wild_vegetation_00": "ai_vegetation_32_32.png",
        }.items():
            with self.subTest(furniture_id=furniture_id):
                furniture = furniture_by_id[furniture_id]
                self.assertEqual(furniture["sprite"], expected_sprite)
                self.assertIn("Nature", furniture["categories"])
                self.assertFalse(furniture["moveable"])
                self.assertTrue(
                    (ROOT / "Mods" / "Dimensionfall" / "Furniture" / expected_sprite).is_file()
                )

        palette_ids = {
            entry["id"] for entry in recipe["furniture_palette"]["clearing_groundcover"]
        }
        self.assertEqual(palette_ids, {"rock_field_00", "wild_vegetation_00"})

    def test_area_rectangle_serializes_runtime_area_definition_at_explicit_level(self):
        recipe = valid_recipe()
        recipe["areas"] = [
            {
                "id": "meadow_clearing",
                "spawn_chance": 100,
                "rotate_random": False,
                "pick_one": False,
                "tiles": [{"id": "grass_dirt_00", "count": 1}],
                "entities": [],
            }
        ]
        recipe["operations"] = [
            {
                "type": "rectangle",
                "x": 0,
                "y": 0,
                "width": 32,
                "height": 32,
                "z": 1,
                "tile": {"id": "grass_plain_01"},
            },
            {
                "type": "area_rectangle",
                "area": "meadow_clearing",
                "x": 4,
                "y": 5,
                "width": 3,
                "height": 2,
                "z": 1,
                "rotation": 90,
            }
        ]

        generated = generate_map(recipe, TILES_PATH)

        self.assertEqual(generated["areas"], recipe["areas"])
        self.assertEqual(generated["levels"][10][5 * 32 + 4]["id"], "grass_plain_01")
        self.assertNotIn("areas", generated["levels"][10][5 * 32 + 4])
        for y in range(5, 7):
            for x in range(4, 7):
                self.assertEqual(
                    generated["levels"][11][y * 32 + x]["areas"],
                    [{"id": "meadow_clearing", "rotation": 90}],
                )

    def test_area_rectangle_rejects_unknown_area_duplicate_membership_and_empty_cells(self):
        base_area = {
            "id": "meadow_clearing",
            "spawn_chance": 100,
            "rotate_random": False,
            "pick_one": False,
            "tiles": [{"id": "grass_dirt_00", "count": 1}],
            "entities": [],
        }
        cases = [
            (
                [{"type": "area_rectangle", "area": "unknown", "x": 0, "y": 0, "width": 1, "height": 1}],
                "references unknown area 'unknown'",
            ),
            (
                [
                    {"type": "area_rectangle", "area": "meadow_clearing", "x": 0, "y": 0, "width": 1, "height": 1},
                    {"type": "area_rectangle", "area": "meadow_clearing", "x": 0, "y": 0, "width": 1, "height": 1},
                ],
                r"duplicates area 'meadow_clearing' at \[0, 0\]",
            ),
        ]
        for operations, expected_message in cases:
            with self.subTest(operations=operations):
                recipe = valid_recipe()
                recipe["areas"] = [base_area]
                recipe["operations"] = operations
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

        recipe = valid_recipe()
        recipe["areas"] = [base_area]
        recipe["operations"] = [
            {"type": "set", "x": 0, "y": 0, "tile": None},
            {"type": "area_rectangle", "area": "meadow_clearing", "x": 0, "y": 0, "width": 1, "height": 1},
        ]
        with self.assertRaisesRegex(RecipeError, r"requires supporting terrain at \[0, 0\]"):
            generate_map(recipe, TILES_PATH)

    def test_room_rectangle_serializes_authored_semantic_membership(self):
        recipe = valid_recipe()
        recipe["rooms"] = [
            {"id": "office", "kind": "enclosed"},
            {"id": "garage_bay", "kind": "covered_open"},
            {"id": "damaged_store", "kind": "ruin"},
        ]
        recipe["operations"] = [
            {
                "type": "rectangle",
                "x": 0,
                "y": 0,
                "width": 32,
                "height": 32,
                "z": 1,
                "tile": {"id": "concrete_00"},
            },
            {
                "type": "room_rectangle",
                "room": "garage_bay",
                "x": 4,
                "y": 3,
                "width": 3,
                "height": 2,
                "z": 1,
            },
        ]

        generated = generate_map(recipe, TILES_PATH)

        self.assertEqual(generated["rooms"], recipe["rooms"])
        self.assertNotIn("rooms", generated["levels"][10][3 * 32 + 4])
        for y in range(3, 5):
            for x in range(4, 7):
                self.assertEqual(generated["levels"][11][y * 32 + x]["rooms"], ["garage_bay"])

    def test_room_rectangle_rejects_invalid_definitions_and_ambiguous_membership(self):
        valid_rooms = [{"id": "office", "kind": "enclosed"}]
        invalid_rooms = [
            ([{"id": "office", "kind": "unknown"}], "unsupported kind 'unknown'"),
            ([{"id": "office", "kind": "enclosed"}, {"id": "office", "kind": "ruin"}], "duplicate room ID 'office'"),
            ([{"id": "office", "kind": "enclosed", "extra": True}], "unknown rooms\\[0\\] field 'extra'"),
        ]
        for rooms, expected_message in invalid_rooms:
            with self.subTest(rooms=rooms):
                recipe = valid_recipe()
                recipe["rooms"] = rooms
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

        invalid_operations = [
            ([{"type": "room_rectangle", "room": "unknown", "x": 0, "y": 0, "width": 1, "height": 1}], "references unknown room 'unknown'"),
            ([
                {"type": "room_rectangle", "room": "office", "x": 0, "y": 0, "width": 1, "height": 1},
                {"type": "room_rectangle", "room": "office", "x": 0, "y": 0, "width": 1, "height": 1},
            ], r"duplicates room membership at \[0, 0\]"),
            ([{"type": "room_rectangle", "room": "office", "x": 0, "y": 0, "width": 1, "height": 1, "rotation": 90}], "unknown operations\\[0\\] field 'rotation'"),
        ]
        for operations, expected_message in invalid_operations:
            with self.subTest(operations=operations):
                recipe = valid_recipe()
                recipe["rooms"] = valid_rooms
                recipe["operations"] = operations
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

        recipe = valid_recipe()
        recipe["rooms"] = valid_rooms
        recipe["operations"] = [
            {"type": "set", "x": 0, "y": 0, "tile": None},
            {"type": "room_rectangle", "room": "office", "x": 0, "y": 0, "width": 1, "height": 1},
        ]
        with self.assertRaisesRegex(RecipeError, r"requires supporting terrain at \[0, 0\]"):
            generate_map(recipe, TILES_PATH)

    def test_room_connections_preserve_existing_door_features(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "concrete_00"}
        recipe["rooms"] = [
            {"id": "office", "kind": "enclosed"},
            {"id": "garage_bay", "kind": "covered_open"},
        ]
        recipe["operations"] = [
            {"type": "room_rectangle", "room": "office", "x": 8, "y": 8, "width": 4, "height": 4},
            {"type": "room_rectangle", "room": "garage_bay", "x": 12, "y": 8, "width": 4, "height": 4},
            {"type": "furniture", "id": "door_wood", "x": 11, "y": 10, "rotation": 0},
            {"type": "furniture", "id": "door_wood", "x": 12, "y": 10, "rotation": 90},
        ]
        recipe["room_connections"] = [
            {
                "id": "office_front_door",
                "at": [11, 10],
                "z": 0,
                "from": {"kind": "room", "id": "office"},
                "to": {"kind": "exterior"},
            },
            {
                "id": "office_to_garage",
                "at": [12, 10],
                "z": 0,
                "from": {"kind": "room", "id": "office"},
                "to": {"kind": "room", "id": "garage_bay"},
            },
        ]

        generated = generate_map(recipe, TILES_PATH)

        self.assertEqual(generated["room_connections"], recipe["room_connections"])
        level = generated["levels"][10]
        self.assertEqual(level[10 * 32 + 11]["feature"], {
            "type": "furniture",
            "id": "door_wood",
            "rotation": 0,
            "itemgroups": [],
        })
        self.assertEqual(level[10 * 32 + 12]["feature"], {
            "type": "furniture",
            "id": "door_wood",
            "rotation": 90,
            "itemgroups": [],
        })

    def test_room_boundaries_preserve_existing_wall_tiles_and_connected_doors(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "concrete_00"}
        recipe["rooms"] = [{"id": "office", "kind": "enclosed"}]
        recipe["operations"] = [
            {"type": "room_rectangle", "room": "office", "x": 8, "y": 8, "width": 4, "height": 4},
            {"type": "set", "x": 8, "y": 7, "tile": {"id": "brick_wall_00"}},
            {"type": "furniture", "id": "door_wood", "x": 11, "y": 10, "rotation": 0},
        ]
        recipe["room_connections"] = [{
            "id": "office_front_door",
            "at": [11, 10],
            "z": 0,
            "from": {"kind": "room", "id": "office"},
            "to": {"kind": "exterior"},
        }]
        recipe["room_boundaries"] = [
            {
                "id": "office_north_wall",
                "room": "office",
                "at": [8, 7],
                "z": 0,
                "element": "wall_tile",
            },
            {
                "id": "office_front_opening",
                "room": "office",
                "at": [11, 10],
                "z": 0,
                "element": "door_furniture",
            },
        ]

        generated = generate_map(recipe, TILES_PATH)

        self.assertEqual(generated["room_boundaries"], recipe["room_boundaries"])
        level = generated["levels"][10]
        self.assertEqual(level[7 * 32 + 8]["id"], "brick_wall_00")
        self.assertEqual(level[10 * 32 + 11]["feature"]["id"], "door_wood")

    def test_room_boundaries_reject_invalid_schema_and_physical_targets(self):
        valid_boundary = {
            "id": "office_north_wall",
            "room": "office",
            "at": [8, 7],
            "z": 0,
            "element": "wall_tile",
        }
        valid_connection = {
            "id": "office_front_door",
            "at": [11, 10],
            "z": 0,
            "from": {"kind": "room", "id": "office"},
            "to": {"kind": "exterior"},
        }
        cases = [
            ("not-an-array", "room_boundaries must be an array"),
            ([{**valid_boundary, "extra": True}], "unknown room_boundaries\\[0\\] field 'extra'"),
            ([{**valid_boundary, "room": "missing"}], "references unknown room 'missing'"),
            ([{**valid_boundary, "at": [32, 7]}], "must be within map bounds"),
            ([{**valid_boundary, "z": -11}], "must be an integer from -10 through 10"),
            ([{**valid_boundary, "element": "wall_furniture"}], "unsupported element 'wall_furniture'"),
            ([{**valid_boundary, "at": [0, 0]}], "Wall-category tile"),
            ([{**valid_boundary, "at": [8, 6]}], "must be cardinally adjacent"),
            ([{**valid_boundary, "element": "door_furniture", "at": [11, 10]}], "must match a room connection"),
            ([valid_boundary, {**valid_boundary, "id": "duplicate_target"}], r"duplicates boundary target for room 'office' at z 0 \[8, 7\]"),
        ]
        for boundaries, expected_message in cases:
            with self.subTest(boundaries=boundaries):
                recipe = valid_recipe()
                recipe["base_tile"] = {"id": "concrete_00"}
                recipe["rooms"] = [{"id": "office", "kind": "enclosed"}]
                recipe["operations"] = [
                    {"type": "room_rectangle", "room": "office", "x": 8, "y": 8, "width": 4, "height": 4},
                    {"type": "set", "x": 8, "y": 7, "tile": {"id": "brick_wall_00"}},
                    {"type": "set", "x": 8, "y": 6, "tile": {"id": "brick_wall_00"}},
                    {"type": "furniture", "id": "door_wood", "x": 11, "y": 10, "rotation": 0},
                ]
                recipe["room_boundaries"] = boundaries
                if boundaries == [{**valid_boundary, "element": "door_furniture", "at": [11, 10]}]:
                    recipe["room_connections"] = []
                else:
                    recipe["room_connections"] = [valid_connection]
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_room_connections_reject_invalid_schema_and_targets(self):
        base_connection = {
            "id": "office_front_door",
            "at": [11, 10],
            "z": 0,
            "from": {"kind": "room", "id": "office"},
            "to": {"kind": "exterior"},
        }
        invalid_connections = [
            ("not-an-array", "room_connections must be an array"),
            ([{"id": "office_front_door", "at": [11, 10], "z": 0, "from": {"kind": "room", "id": "office"}, "to": {"kind": "exterior"}, "extra": True}], "unknown room_connections\\[0\\] field 'extra'"),
            ([{**base_connection, "from": {"kind": "room", "id": "missing"}}], "references unknown room 'missing'"),
            ([{**base_connection, "to": {"kind": "exterior", "id": "forbidden"}}], "must define only kind"),
            ([{**base_connection, "to": {"kind": "room", "id": "office"}}], "must connect distinct endpoints"),
            ([{**base_connection, "at": [32, 10]}], "must be within map bounds"),
            ([{**base_connection, "z": 11}], "must be an integer from -10 through 10"),
            ([{**base_connection, "at": [0, 0]}], "must reference door-capable furniture"),
            ([base_connection, {**base_connection, "id": "another_door"}], r"duplicates door target at z 0 \[11, 10\]"),
        ]
        for connections, expected_message in invalid_connections:
            with self.subTest(connections=connections):
                recipe = valid_recipe()
                recipe["base_tile"] = {"id": "concrete_00"}
                recipe["rooms"] = [{"id": "office", "kind": "enclosed"}]
                recipe["operations"] = [
                    {"type": "furniture", "id": "door_wood", "x": 11, "y": 10, "rotation": 0},
                ]
                recipe["room_connections"] = connections
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_area_entities_require_known_runtime_type_catalog_ids_and_positive_counts(self):
        known_entity_ids = {
            "furniture": json.loads(FURNITURES_PATH.read_text(encoding="utf-8"))[0]["id"],
            "mob": json.loads(MOBS_PATH.read_text(encoding="utf-8"))[0]["id"],
            "mobgroup": json.loads(MOBGROUPS_PATH.read_text(encoding="utf-8"))[0]["id"],
            "itemgroup": json.loads(ITEMGROUPS_PATH.read_text(encoding="utf-8"))[0]["id"],
        }

        for entity_type, entity_id in known_entity_ids.items():
            with self.subTest(entity_type=entity_type):
                recipe = valid_recipe()
                recipe["areas"] = [{
                    "id": "runtime_entities",
                    "spawn_chance": 100,
                    "rotate_random": False,
                    "pick_one": False,
                    "tiles": [{"id": "grass_dirt_00", "count": 1}],
                    "entities": [{"id": entity_id, "type": entity_type, "count": 1}],
                }]
                generated = generate_map(recipe, TILES_PATH)
                self.assertEqual(generated["areas"][0]["entities"], recipe["areas"][0]["entities"])

        invalid_entities = [
            ({"id": "table_round_wood", "type": "unsupported", "count": 1}, "unsupported type"),
            ({"id": "missing", "type": "furniture", "count": 1}, "unknown furniture"),
            ({"id": "missing", "type": "mob", "count": 1}, "unknown mob"),
            ({"id": "missing", "type": "mobgroup", "count": 1}, "unknown mobgroup"),
            ({"id": "missing", "type": "itemgroup", "count": 1}, "unknown itemgroup"),
            ({"id": "table_round_wood", "type": "furniture", "count": 0}, "positive integer"),
            ({"id": "table_round_wood", "type": "furniture", "count": True}, "positive integer"),
            ({"id": "table_round_wood", "type": "furniture", "count": 1.5}, "positive integer"),
        ]
        for entity, expected_message in invalid_entities:
            with self.subTest(entity=entity):
                recipe = valid_recipe()
                recipe["areas"] = [{
                    "id": "runtime_entities",
                    "spawn_chance": 100,
                    "rotate_random": False,
                    "pick_one": False,
                    "tiles": [{"id": "grass_dirt_00", "count": 1}],
                    "entities": [entity],
                }]
                with self.assertRaisesRegex(RecipeError, expected_message):
                    generate_map(recipe, TILES_PATH)

    def test_room_semantics_example_preserves_authored_labels(self):
        recipe_path = ROOT / "Tools" / "examples" / "map_recipe_room_semantics.json"
        generated = generate_map(
            json.loads(recipe_path.read_text(encoding="utf-8")), TILES_PATH
        )

        self.assertEqual(generated["rooms"], [
            {"id": "office", "kind": "enclosed"},
            {"id": "garage_bay", "kind": "covered_open"},
            {"id": "ruined_store", "kind": "ruin"},
        ])
        level = generated["levels"][10]
        expected_memberships = {
            "office": {(x, y) for y in range(7, 15) for x in range(4, 12)},
            "garage_bay": {(x, y) for y in range(7, 15) for x in range(12, 22)},
            "ruined_store": {(x, y) for y in range(17, 25) for x in range(7, 19)},
        }
        for room_id, expected_cells in expected_memberships.items():
            actual_cells = {
                (index % 32, index // 32)
                for index, tile in enumerate(level)
                if tile.get("rooms") == [room_id]
            }
            self.assertEqual(actual_cells, expected_cells)
        self.assertEqual(level[7 * 32 + 11]["id"], "concrete_00")
        self.assertEqual(level[7 * 32 + 12]["id"], "concrete_00")
        self.assertNotIn("rooms", level[0])

    def test_room_connections_example_preserves_semantic_door_links(self):
        recipe_path = ROOT / "Tools" / "examples" / "map_recipe_room_connections.json"
        generated = generate_map(
            json.loads(recipe_path.read_text(encoding="utf-8")), TILES_PATH
        )

        self.assertEqual([room["id"] for room in generated["rooms"]], [
            "office", "garage_bay", "ruined_store"
        ])
        self.assertEqual(generated["room_connections"], [
            {
                "id": "office_front_door",
                "at": [11, 10],
                "z": 0,
                "from": {"kind": "room", "id": "office"},
                "to": {"kind": "exterior"},
            },
            {
                "id": "office_to_garage",
                "at": [12, 10],
                "z": 0,
                "from": {"kind": "room", "id": "office"},
                "to": {"kind": "room", "id": "garage_bay"},
            },
        ])
        level = generated["levels"][10]
        for x, rotation in ((11, 0), (12, 90)):
            self.assertEqual(level[10 * 32 + x]["feature"], {
                "type": "furniture",
                "id": "door_wood",
                "rotation": rotation,
                "itemgroups": [],
            })
        self.assertEqual(
            generated,
            generate_map(json.loads(recipe_path.read_text(encoding="utf-8")), TILES_PATH),
        )

    def test_area_meadow_example_matches_its_runtime_area_boundary(self):
        recipe_path = ROOT / "Tools" / "examples" / "map_recipe_area_meadow.json"
        generated = generate_map(
            json.loads(recipe_path.read_text(encoding="utf-8")), TILES_PATH
        )

        self.assertEqual(generated["areas"], [
            {
                "id": "meadow_clearing",
                "spawn_chance": 100,
                "rotate_random": False,
                "pick_one": False,
                "tiles": [{"id": "grass_dirt_00", "count": 1}],
                "entities": [],
            }
        ])
        memberships = [
            (index % 32, index // 32)
            for index, tile in enumerate(generated["levels"][10])
            if tile.get("areas") == [{"id": "meadow_clearing", "rotation": 0}]
        ]
        self.assertEqual(len(memberships), 144)
        self.assertEqual(set(memberships), {
            (x, y) for y in range(10, 22) for x in range(10, 22)
        })
        self.assertTrue(
            all(
                generated["levels"][10][y * 32 + x]["id"] == "grass_dirt_00"
                for x, y in memberships
            )
        )

    def test_area_entity_clearing_example_preserves_runtime_entity_selection(self):
        recipe_path = ROOT / "Tools" / "examples" / "map_recipe_area_entity_clearing.json"
        recipe = json.loads(recipe_path.read_text(encoding="utf-8"))
        generated = generate_map(recipe, TILES_PATH)

        self.assertEqual(generate_map(recipe, TILES_PATH), generated)
        self.assertEqual(generated["areas"], [{
            "id": "stump_clearing",
            "spawn_chance": 100,
            "rotate_random": False,
            "pick_one": False,
            "tiles": [{"id": "grass_dirt_00", "count": 100}],
            "entities": [{
                "id": "burned_tree_stump",
                "type": "furniture",
                "count": 1,
            }],
        }])
        memberships = [
            (index % 32, index // 32, tile)
            for index, tile in enumerate(generated["levels"][10])
            if tile.get("areas") == [{"id": "stump_clearing", "rotation": 0}]
        ]
        self.assertEqual(len(memberships), 144)
        self.assertEqual(
            {(x, y) for x, y, _ in memberships},
            {(x, y) for y in range(10, 22) for x in range(10, 22)},
        )
        self.assertTrue(all(tile["id"] == "grass_dirt_00" for _, _, tile in memberships))
        self.assertTrue(all("feature" not in tile for _, _, tile in memberships))

    def test_multi_level_examples_have_supported_slope_endpoints(self):
        high_direction = {
            0: (0, -1),
            90: (1, 0),
            180: (0, 1),
            270: (-1, 0),
        }
        for filename in (
            "map_recipe_two_level_hill.json",
            "map_recipe_two_level_depression.json",
        ):
            with self.subTest(filename=filename):
                recipe_path = ROOT / "Tools" / "examples" / filename
                generated = generate_map(
                    json.loads(recipe_path.read_text(encoding="utf-8")), TILES_PATH
                )
                slopes = []
                for level_index, level in enumerate(generated["levels"]):
                    for tile_index, tile in enumerate(level):
                        if tile.get("id") == "grass_ramp_00":
                            slopes.append((level_index, tile_index, tile))

                self.assertEqual(len(slopes), 4)
                for level_index, tile_index, tile in slopes:
                    x = tile_index % 32
                    y = tile_index // 32
                    delta_x, delta_y = high_direction[tile.get("rotation", 0)]
                    high_index = (y + delta_y) * 32 + x + delta_x
                    low_index = (y - delta_y) * 32 + x - delta_x
                    self.assertTrue(generated["levels"][level_index][high_index])
                    self.assertTrue(generated["levels"][level_index - 1][low_index])

    def test_invalid_unicode_metadata_is_rejected_with_a_clear_error(self):
        with tempfile.TemporaryDirectory() as directory:
            directory_path = Path(directory)
            recipe = valid_recipe()
            recipe["name"] = "\ud800"
            recipe_path = directory_path / "recipe.json"
            recipe_path.write_text(json.dumps(recipe), encoding="utf-8")

            with self.assertRaisesRegex(ValueError, "name must contain valid Unicode"):
                write_map(
                    recipe_path,
                    directory_path / "generated_test_map.json",
                    TILES_PATH,
                )

    def test_malformed_tile_database_is_rejected_with_a_clear_error(self):
        with tempfile.TemporaryDirectory() as directory:
            tiles_path = Path(directory) / "Tiles.json"
            tiles_path.write_text("42", encoding="utf-8")

            with self.assertRaisesRegex(
                ValueError, "tile database must be a JSON array"
            ):
                generate_map(valid_recipe(), tiles_path)

    def test_output_filename_must_match_map_id(self):
        with tempfile.TemporaryDirectory() as directory:
            recipe_path = Path(directory) / "recipe.json"
            recipe_path.write_text(json.dumps(valid_recipe()), encoding="utf-8")

            with self.assertRaisesRegex(
                ValueError, "must be named generated_test_map.json"
            ):
                write_map(recipe_path, Path(directory) / "different.json", TILES_PATH)

    def test_write_map_protects_existing_output_unless_overwrite_is_enabled(self):
        with tempfile.TemporaryDirectory() as directory:
            directory_path = Path(directory)
            recipe_path = directory_path / "recipe.json"
            output_path = directory_path / "generated_test_map.json"
            recipe_path.write_text(json.dumps(valid_recipe()), encoding="utf-8")
            output_path.write_text("original", encoding="utf-8")

            with self.assertRaisesRegex(FileExistsError, "use --overwrite"):
                write_map(recipe_path, output_path, TILES_PATH)
            self.assertEqual(output_path.read_text(encoding="utf-8"), "original")

            write_map(recipe_path, output_path, TILES_PATH, overwrite=True)
            self.assertEqual(
                json.loads(output_path.read_text(encoding="utf-8"))["id"],
                "generated_test_map",
            )


class MapValidatorDimensionTests(unittest.TestCase):
    def validate(self, map_data):
        with tempfile.TemporaryDirectory() as directory:
            map_path = Path(directory) / "test_map.json"
            map_path.write_text(json.dumps(map_data), encoding="utf-8")
            validator = MapValidator()
            validator.validate_map(str(map_path))
            return validator.errors

    def test_rejects_nonstandard_map_width(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["mapwidth"] = 31

        errors = self.validate(map_data)

        self.assertTrue(any("mapwidth" in error for error in errors))
        self.assertTrue(any("expected 32, actual 31" in error for error in errors))
        self.assertTrue(all("test_map.json" in error for error in errors))

    def test_rejects_nonstandard_map_height(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["mapheight"] = 33

        errors = self.validate(map_data)

        self.assertTrue(any("mapheight" in error for error in errors))
        self.assertTrue(any("expected 32, actual 33" in error for error in errors))

    def test_rejects_populated_level_with_too_few_tiles(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["levels"][10].pop()

        errors = self.validate(map_data)

        self.assertTrue(any("Level 10" in error for error in errors))
        self.assertTrue(any("expected 1024, actual 1023" in error for error in errors))

    def test_rejects_populated_level_with_too_many_tiles(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["levels"][10].append({})

        errors = self.validate(map_data)

        self.assertTrue(any("Level 10" in error for error in errors))
        self.assertTrue(any("expected 1024, actual 1025" in error for error in errors))

    def test_accepts_empty_unused_levels(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)

        self.assertEqual(map_data["levels"][0], [])
        self.assertEqual(self.validate(map_data), [])

    def test_rejects_incorrect_level_count(self):
        for count in (20, 22):
            with self.subTest(count=count):
                map_data = generate_map(valid_recipe(), TILES_PATH)
                if count == 20:
                    map_data["levels"].pop()
                else:
                    map_data["levels"].append([])

                errors = self.validate(map_data)

                self.assertTrue(any("Level count" in error for error in errors))
                self.assertTrue(
                    any(f"expected 21, actual {count}" in error for error in errors)
                )

    def test_validates_furniture_feature_structure(self):
        invalid_features = [
            ("not-an-object", "feature is not an object"),
            ({"type": "furniture", "rotation": 0}, "invalid or missing ID"),
            (
                {"type": "furniture", "id": "bench_garden", "rotation": 45},
                "invalid rotation",
            ),
            (
                {
                    "type": "furniture",
                    "id": "bench_garden",
                    "rotation": 0,
                    "itemgroups": [1],
                },
                "itemgroups must be an array of strings",
            ),
            (
                {
                    "type": "furniture",
                    "id": "bench_garden",
                    "rotation": 0,
                    "unexpected": True,
                },
                "unknown field 'unexpected'",
            ),
        ]
        for feature, expected_message in invalid_features:
            with self.subTest(feature=feature):
                map_data = generate_map(valid_recipe(), TILES_PATH)
                map_data["levels"][10][0]["feature"] = feature

                errors = self.validate(map_data)

                self.assertTrue(any(expected_message in error for error in errors))

    def test_validates_area_reference_structure(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["areas"] = "not-an-array"
        errors = self.validate(map_data)
        self.assertTrue(any("top-level areas must be an array" in error for error in errors))

        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["areas"] = [{"id": "meadow_clearing"}]
        map_data["levels"][10][0]["areas"] = "not-an-array"

        errors = self.validate(map_data)

        self.assertTrue(any("areas must be an array" in error for error in errors))

        map_data["levels"][10][0]["areas"] = [
            {"id": "meadow_clearing", "rotation": 45}
        ]
        errors = self.validate(map_data)
        self.assertTrue(any("invalid area rotation" in error for error in errors))

    def test_validates_area_entity_definition_structure(self):
        invalid_entities = [
            ("not-an-array", "entities must be an array"),
            (["not-an-object"], "entity at index 0 is not an object"),
            ([{"id": "burned_tree_stump", "type": "furniture"}], "missing required field 'count'"),
            ([{"id": "burned_tree_stump", "type": "unsupported", "count": 1}], "unsupported entity type"),
            ([{"id": "burned_tree_stump", "type": "furniture", "count": 0}], "count must be a positive number"),
            ([{"id": "burned_tree_stump", "type": "furniture", "count": "one"}], "count must be a positive number"),
        ]
        for entities, expected_message in invalid_entities:
            with self.subTest(entities=entities):
                map_data = generate_map(valid_recipe(), TILES_PATH)
                map_data["areas"] = [{
                    "id": "stump_clearing",
                    "entities": entities,
                }]

                errors = self.validate(map_data)

                self.assertTrue(any(expected_message in error for error in errors))

    def test_validates_room_definition_and_membership_structure(self):
        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["rooms"] = "not-an-array"
        errors = self.validate(map_data)
        self.assertTrue(any("top-level rooms must be an array" in error for error in errors))

        invalid_rooms = [
            (["not-an-object"], "Room at index 0 is not an object"),
            ([{"kind": "enclosed"}], "missing required field 'id'"),
            ([{"id": "office", "kind": "unknown"}], "unsupported room kind 'unknown'"),
            ([{"id": "office", "kind": "enclosed", "extra": True}], "unknown field 'extra'"),
            ([{"id": "office", "kind": "enclosed"}, {"id": "office", "kind": "ruin"}], "Duplicate room ID"),
        ]
        for rooms, expected_message in invalid_rooms:
            with self.subTest(rooms=rooms):
                map_data = generate_map(valid_recipe(), TILES_PATH)
                map_data["rooms"] = rooms
                errors = self.validate(map_data)
                self.assertTrue(any(expected_message in error for error in errors))

        map_data = generate_map(valid_recipe(), TILES_PATH)
        map_data["rooms"] = [{"id": "office", "kind": "enclosed"}]
        invalid_memberships = [
            ("not-an-array", "rooms must be an array"),
            (["missing"], "references non-existent room 'missing'"),
            (["office", "office"], "must contain exactly one room ID"),
        ]
        for membership, expected_message in invalid_memberships:
            with self.subTest(membership=membership):
                map_data["levels"][10][0]["rooms"] = membership
                errors = self.validate(map_data)
                self.assertTrue(any(expected_message in error for error in errors))

        map_data["levels"][10][0] = {"rooms": ["office"]}
        errors = self.validate(map_data)
        self.assertTrue(any("missing required 'id'" in error for error in errors))

        map_data["levels"][10][0] = {"id": "", "rooms": ["office"]}
        errors = self.validate(map_data)
        self.assertTrue(any("room membership requires terrain" in error for error in errors))

    def test_validates_room_connection_structure_and_door_targets(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "concrete_00"}
        recipe["rooms"] = [{"id": "office", "kind": "enclosed"}]
        recipe["operations"] = [
            {"type": "furniture", "id": "door_wood", "x": 11, "y": 10, "rotation": 0},
        ]
        recipe["room_connections"] = [{
            "id": "office_front_door",
            "at": [11, 10],
            "z": 0,
            "from": {"kind": "room", "id": "office"},
            "to": {"kind": "exterior"},
        }]
        valid_map = generate_map(recipe, TILES_PATH)
        self.assertEqual(self.validate(valid_map), [])

        invalid_maps = []
        malformed_root = valid_map.copy()
        malformed_root["room_connections"] = "not-an-array"
        invalid_maps.append((malformed_root, "top-level room_connections must be an array"))

        missing_room = json.loads(json.dumps(valid_map))
        missing_room["room_connections"][0]["from"]["id"] = "missing"
        invalid_maps.append((missing_room, "references non-existent room 'missing'"))

        missing_feature = json.loads(json.dumps(valid_map))
        missing_feature["levels"][10][10 * 32 + 11].pop("feature")
        invalid_maps.append((missing_feature, "must reference door-capable furniture"))

        duplicate_target = json.loads(json.dumps(valid_map))
        duplicate_target["room_connections"].append({
            **duplicate_target["room_connections"][0], "id": "another_door"
        })
        invalid_maps.append((duplicate_target, "duplicates door target"))

        for map_data, expected_message in invalid_maps:
            with self.subTest(expected_message=expected_message):
                errors = self.validate(map_data)
                self.assertTrue(any(expected_message in error for error in errors))
    def test_validates_room_boundary_structure_and_existing_sources(self):
        recipe = valid_recipe()
        recipe["base_tile"] = {"id": "concrete_00"}
        recipe["rooms"] = [{"id": "office", "kind": "enclosed"}]
        recipe["operations"] = [
            {"type": "room_rectangle", "room": "office", "x": 8, "y": 8, "width": 4, "height": 4},
            {"type": "set", "x": 8, "y": 7, "tile": {"id": "brick_wall_00"}},
            {"type": "set", "x": 8, "y": 6, "tile": {"id": "brick_wall_00"}},
            {"type": "furniture", "id": "door_wood", "x": 11, "y": 10, "rotation": 0},
        ]
        recipe["room_connections"] = [{
            "id": "office_front_door",
            "at": [11, 10],
            "z": 0,
            "from": {"kind": "room", "id": "office"},
            "to": {"kind": "exterior"},
        }]
        recipe["room_boundaries"] = [
            {"id": "office_north_wall", "room": "office", "at": [8, 7], "z": 0, "element": "wall_tile"},
            {"id": "office_front_opening", "room": "office", "at": [11, 10], "z": 0, "element": "door_furniture"},
        ]
        valid_map = generate_map(recipe, TILES_PATH)
        self.assertEqual(self.validate(valid_map), [])

        invalid_maps = []
        malformed_root = json.loads(json.dumps(valid_map))
        malformed_root["room_boundaries"] = "not-an-array"
        invalid_maps.append((malformed_root, "top-level room_boundaries must be an array"))

        missing_room = json.loads(json.dumps(valid_map))
        missing_room["room_boundaries"][0]["room"] = "missing"
        invalid_maps.append((missing_room, "references non-existent room 'missing'"))

        non_wall = json.loads(json.dumps(valid_map))
        non_wall["room_boundaries"][0]["at"] = [0, 0]
        invalid_maps.append((non_wall, "must reference a Wall-category tile"))

        non_adjacent_wall = json.loads(json.dumps(valid_map))
        non_adjacent_wall["room_boundaries"][0]["at"] = [8, 6]
        invalid_maps.append((non_adjacent_wall, "must be cardinally adjacent"))

        unmatched_door = json.loads(json.dumps(valid_map))
        unmatched_door["room_connections"] = []
        invalid_maps.append((unmatched_door, "must match a room connection"))

        duplicate_target = json.loads(json.dumps(valid_map))
        duplicate_target["room_boundaries"].append({
            **duplicate_target["room_boundaries"][0], "id": "duplicate_target"
        })
        invalid_maps.append((duplicate_target, "duplicates boundary target"))

        for map_data, expected_message in invalid_maps:
            with self.subTest(expected_message=expected_message):
                errors = self.validate(map_data)
                self.assertTrue(any(expected_message in error for error in errors))
    def test_room_boundaries_example_preserves_existing_physical_sources(self):
        recipe_path = ROOT / "Tools" / "examples" / "map_recipe_room_boundaries.json"
        generated = generate_map(
            json.loads(recipe_path.read_text(encoding="utf-8")), TILES_PATH
        )

        self.assertEqual([boundary["id"] for boundary in generated["room_boundaries"]], [
            "office_north_wall",
            "office_west_wall",
            "garage_east_wall",
            "ruin_north_wall",
            "office_front_opening",
            "office_garage_opening",
            "garage_office_opening",
        ])
        level = generated["levels"][10]
        for x, y in ((8, 7), (7, 8), (16, 8), (8, 16)):
            self.assertEqual(level[y * 32 + x]["id"], "brick_wall_00")
        self.assertEqual(level[10 * 32 + 11]["feature"]["id"], "door_wood")
        self.assertEqual(level[10 * 32 + 12]["feature"]["id"], "door_wood")


if __name__ == "__main__":
    unittest.main()
